[LauncherOrder]
usr\share\applications\bolide-fitness.desktop=0
usr\share\applications\asteroid-calendar.desktop=1
usr\share\applications\asteroid-alarmclock.desktop=2
usr\share\applications\asteroid-calculator.desktop=3
usr\share\applications\asteroid-diamonds.desktop=4
usr\share\applications\asteroid-flashlight.desktop=5
usr\share\applications\asteroid-music.desktop=6
usr\share\applications\asteroid-stopwatch.desktop=7
usr\share\applications\asteroid-timer.desktop=8
usr\share\applications\asteroid-weather.desktop=9
